use super::test_support::*;
use super::*;

#[test]
fn git_link_command_parses_commit_and_expectation() {
    let cli = Cli::try_parse_from([
        "susumu",
        "git",
        "link",
        "abc123",
        "e_checkout_sequence",
        "--kind",
        "documentation",
    ])
    .expect("parse git link");

    match cli.command.expect("command") {
        Command::Git {
            command: Some(GitCommand::Link(args)),
            ..
        } => {
            assert_eq!(args.commit, "abc123");
            assert_eq!(args.expectation, "e_checkout_sequence");
            assert_eq!(WorkKind::from(args.kind), WorkKind::Documentation);
        }
        other => panic!("expected git link command, got {other:?}"),
    }
}

#[test]
fn work_kind_accepts_infrastructure() {
    let kind = "infrastructure"
        .parse::<WorkKind>()
        .expect("parse infrastructure kind");

    assert_eq!(kind, WorkKind::Infrastructure);
    assert_eq!(kind.to_string(), "infrastructure");
}

#[test]
fn git_link_command_parses_infrastructure_kind() {
    let cli = Cli::try_parse_from([
        "susumu",
        "git",
        "link",
        "abc123",
        "e_ci_artifacts",
        "--kind",
        "infrastructure",
    ])
    .expect("parse git link infrastructure kind");

    match cli.command.expect("command") {
        Command::Git {
            command: Some(GitCommand::Link(args)),
            ..
        } => {
            assert_eq!(args.commit, "abc123");
            assert_eq!(args.expectation, "e_ci_artifacts");
            assert_eq!(WorkKind::from(args.kind), WorkKind::Infrastructure);
        }
        other => panic!("expected git link command, got {other:?}"),
    }
}

#[test]
fn git_link_work_targets_explicit_expectation() {
    let artifact = test_artifact();
    let expectation = artifact
        .expectations
        .iter()
        .find(|expectation| expectation.id == "e_checkout_sequence")
        .expect("expectation");
    let commit = test_commit(
        "docs: explain checkout sequence",
        "",
        &["README.md", "docs/checkout.md"],
    );

    let work = work_from_git_link(
        &commit,
        expectation,
        &GitLinkArgs {
            repo: PathBuf::from("."),
            artifact: PathBuf::from(".susumu/project.susu"),
            output: PathBuf::from(".susumu/work.susu"),
            commit: commit.hash.clone(),
            expectation: expectation.id.clone(),
            source: "human:git-link".to_owned(),
            kind: WorkKindArg(WorkKind::Documentation),
            status: WorkStatusArg(WorkStatus::Completed),
            title: None,
            detail: Some("Explicitly linked after review.".to_owned()),
            minify: false,
            json: false,
        },
    );

    assert_eq!(
        work.id,
        git_connection_work_id(&commit.hash, Some(expectation.id.as_str()), false)
    );
    assert!(work.id.starts_with("wk_git_f240cd96a07f2ea7_"));
    assert_eq!(work.target, ExpectationTarget::Workflow);
    assert_eq!(work.subject.as_deref(), Some("w_checkout"));
    assert_eq!(work.expectation_id.as_deref(), Some("e_checkout_sequence"));
    assert_eq!(work.kind, WorkKind::Documentation);
    let expected_evidence = format!("commit:{}", commit.hash);
    assert_eq!(work.evidence.as_deref(), Some(expected_evidence.as_str()));
    assert!(work.detail.contains("Generated by git link."));
    assert!(work.detail.contains("README.md"));
    assert!(work.detail.contains("Explicitly linked after review."));
}

#[test]
fn git_link_work_ids_include_expectation_to_avoid_overwriting_other_links() {
    let mut artifact = test_artifact();
    artifact.expectations.push(Expectation {
        id: "e_second_expectation".to_owned(),
        target: ExpectationTarget::Project,
        subject: None,
        status: ExpectationStatus::Accepted,
        source: "human:test".to_owned(),
        title: "Second expectation".to_owned(),
        detail: "A second expectation can be linked to the same commit.".to_owned(),
    });
    let first = artifact
        .expectations
        .iter()
        .find(|expectation| expectation.id == "e_checkout_sequence")
        .expect("first expectation");
    let second = artifact
        .expectations
        .iter()
        .find(|expectation| expectation.id == "e_second_expectation")
        .expect("second expectation");
    let commit = test_commit("test: verify two expectations", "", &["README.md"]);
    let args = GitLinkArgs {
        repo: PathBuf::from("."),
        artifact: PathBuf::from(".susumu/project.susu"),
        output: PathBuf::from(".susumu/work.susu"),
        commit: commit.hash.clone(),
        expectation: first.id.clone(),
        source: "human:git-link".to_owned(),
        kind: WorkKindArg(WorkKind::Verification),
        status: WorkStatusArg(WorkStatus::Completed),
        title: None,
        detail: None,
        minify: false,
        json: false,
    };

    let first_work = work_from_git_link(&commit, first, &args);
    let second_work = work_from_git_link(
        &commit,
        second,
        &GitLinkArgs {
            expectation: second.id.clone(),
            ..args
        },
    );

    assert_ne!(first_work.id, second_work.id);
    assert!(first_work.id.starts_with("wk_git_f240cd96a07f2ea7_"));
    assert!(second_work.id.starts_with("wk_git_f240cd96a07f2ea7_"));
    assert_eq!(
        first_work.evidence.as_deref(),
        second_work.evidence.as_deref()
    );
    assert_eq!(
        first_work.expectation_id.as_deref(),
        Some("e_checkout_sequence")
    );
    assert_eq!(
        second_work.expectation_id.as_deref(),
        Some("e_second_expectation")
    );
}

#[test]
fn init_writes_starter_expectations() {
    let temp = tempfile::tempdir().expect("tempdir");
    init_repository(&InitArgs {
        target: temp.path().to_path_buf(),
        file: PathBuf::from("expectations.susu"),
        name: Some("Acme Checkout".to_owned()),
        source: "human:test".to_owned(),
        force: false,
    })
    .expect("init should write expectations");

    let expectations =
        read_expectations_file(&temp.path().join("expectations.susu")).expect("expectations");
    assert_eq!(expectations.len(), 3);
    assert_eq!(expectations[0].target, ExpectationTarget::Project);
    assert_eq!(expectations[0].subject, None);
    assert_eq!(expectations[0].status, ExpectationStatus::Accepted);
    assert_eq!(expectations[0].source, "human:test");
    assert!(expectations[0].title.contains("Acme Checkout"));
    assert!(
        expectations[0]
            .detail
            .contains("authored expectations.susu sidecar")
    );
    assert_eq!(expectations[1].status, ExpectationStatus::Proposed);
    assert!(expectations[1].title.contains("primary workflows"));
    assert!(
        expectations[1]
            .detail
            .contains("business or product workflows")
    );
    assert_eq!(expectations[2].status, ExpectationStatus::Proposed);
    assert!(expectations[2].title.contains("verification evidence"));
    assert!(
        expectations[2]
            .detail
            .contains("tests, CI runs, manual reviews")
    );
}

#[test]
fn init_refuses_to_overwrite_without_force() {
    let temp = tempfile::tempdir().expect("tempdir");
    let file = temp.path().join("expectations.susu");
    fs::write(&file, "expectation e_existing target=project subject=- status=accepted source=\"human:test\" title=\"Existing\" detail=\"Existing expectation.\";\n")
        .expect("write existing sidecar");

    let result = init_repository(&InitArgs {
        target: temp.path().to_path_buf(),
        file: PathBuf::from("expectations.susu"),
        name: None,
        source: "human:test".to_owned(),
        force: false,
    });

    assert!(result.is_err());
    let existing = fs::read_to_string(file).expect("read existing sidecar");
    assert!(existing.contains("e_existing"));
}

#[test]
fn directory_scans_auto_merge_expectations_sidecar() {
    let temp = tempfile::tempdir().expect("tempdir");
    fs::write(
        temp.path().join("expectations.susu"),
        "expectation e_auto target=project subject=- status=accepted source=\"human:test\" title=\"Auto loaded\" detail=\"Directory scans should load this sidecar.\";\n",
    )
    .expect("write expectations sidecar");

    let analysis = load_analysis(
        &temp.path().to_path_buf(),
        None,
        None,
        None,
        None,
        None,
        false,
    )
    .expect("load analysis");

    assert!(
        analysis
            .expectations
            .iter()
            .any(|expectation| expectation.id == "e_auto")
    );
}

#[test]
fn directory_scans_auto_merge_verifications_sidecar() {
    let temp = tempfile::tempdir().expect("tempdir");
    fs::write(
        temp.path().join("expectations.susu"),
        "expectation e_auto target=project subject=- status=accepted source=\"human:test\" title=\"Auto loaded\" detail=\"Directory scans should load this sidecar.\";\n",
    )
    .expect("write expectations sidecar");
    fs::write(
        temp.path().join("verifications.susu"),
        "verification v_auto expectation=e_auto status=passed method=\"manual review\" source=\"human:test\" evidence=- basis=- detail=\"Reviewed.\";\n",
    )
    .expect("write verifications sidecar");

    let analysis = load_analysis(
        &temp.path().to_path_buf(),
        None,
        None,
        None,
        None,
        None,
        false,
    )
    .expect("load analysis");

    assert!(
        analysis
            .verifications
            .iter()
            .any(|verification| verification.id == "v_auto")
    );
}

#[test]
fn shortcut_commands_parse_without_subcommands() {
    let review = Cli::try_parse_from(["susumu", "review"]).expect("parse review shortcut");
    match review.command.expect("review command") {
        Command::Review { command, .. } => assert!(command.is_none()),
        other => panic!("expected review shortcut, got {other:?}"),
    }

    let git = Cli::try_parse_from(["susumu", "git"]).expect("parse git shortcut");
    match git.command.expect("git command") {
        Command::Git { command, .. } => assert!(command.is_none()),
        other => panic!("expected git shortcut, got {other:?}"),
    }
}

#[test]
fn expectations_command_parses_search_status_and_json() {
    let cli = Cli::try_parse_from([
        "susumu",
        "expectations",
        "--search",
        "git",
        "--status",
        "accepted",
        "--json",
    ])
    .expect("parse expectations shortcut");

    match cli.command.expect("command") {
        Command::Expectations(args) => {
            assert_eq!(args.search.as_deref(), Some("git"));
            assert_eq!(
                args.status.map(ExpectationStatus::from),
                Some(ExpectationStatus::Accepted)
            );
            assert!(args.json);
        }
        other => panic!("expected expectations shortcut, got {other:?}"),
    }
}

#[test]
fn readiness_command_parses_packet_and_json() {
    let cli = Cli::try_parse_from([
        "susumu",
        "readiness",
        "--packet",
        "custom.review.susu",
        "--max-items",
        "5",
        "--bucket",
        "needs_verification",
        "--search",
        "checkout",
        "--json",
    ])
    .expect("parse readiness shortcut");

    match cli.command.expect("command") {
        Command::Readiness(args) => {
            assert_eq!(args.packet, PathBuf::from("custom.review.susu"));
            assert_eq!(args.max_items, 5);
            assert_eq!(args.bucket.as_deref(), Some("needs_verification"));
            assert_eq!(args.search.as_deref(), Some("checkout"));
            assert!(args.json);
        }
        other => panic!("expected readiness shortcut, got {other:?}"),
    }
}

#[test]
fn expectation_rows_filter_by_search_and_status() {
    let rows = vec![
        ExpectationBrowseRow {
            id: "e_git_links".to_owned(),
            title: "Git links are easy".to_owned(),
            detail: "Users can find expectation ids for git link.".to_owned(),
            target: "project".to_owned(),
            subject: None,
            status: "accepted".to_owned(),
            source: "human:test".to_owned(),
            support_status: Some("partially_supported".to_owned()),
            target_observed: Some(true),
            verification: None,
            work: Some(1),
            decisions: Some(0),
            findings: Some(0),
        },
        ExpectationBrowseRow {
            id: "e_future".to_owned(),
            title: "Future idea".to_owned(),
            detail: "A proposed expectation.".to_owned(),
            target: "project".to_owned(),
            subject: None,
            status: "proposed".to_owned(),
            source: "human:test".to_owned(),
            support_status: Some("needs_support".to_owned()),
            target_observed: Some(true),
            verification: None,
            work: Some(0),
            decisions: Some(0),
            findings: Some(0),
        },
    ];

    let filtered = filter_expectation_rows(rows, Some("git"), Some("accepted"));

    assert_eq!(filtered.len(), 1);
    assert_eq!(filtered[0].id, "e_git_links");
}
